---
title: "vehicle_data_load_and_merge"
author: "jefin joseph"
date: "2022-11-22"
output: html_document
---

```{r load-vehicle-column_description-data}
  
vehicle_vehicle_type_raw <- read_csv(here("data/vehicle_vehicle_type.csv")) %>% 
  clean_names()

vehicle_towing_and_articulation_raw <- read_csv(here("data/vehicle_towing_and_articulation.csv")) %>% 
  clean_names()

vehicle_vehicle_manoeuvre_raw <- read_csv(here("data/vehicle_vehicle_manoeuvre.csv")) %>% 
  clean_names()

vehicle_vehicle_direction_from_raw <- read_csv(here("data/vehicle_vehicle_direction_from.csv")) %>% 
  clean_names()

vehicle_vehicle_direction_to_raw <- read_csv(here("data/vehicle_vehicle_direction_to.csv")) %>% 
  clean_names()

vehicle_vehicle_location_restricted_lane_raw <- read_csv(here("data/vehicle_vehicle_location_restricted_lane.csv")) %>% 
  clean_names()

vehicle_junction_location_raw <- read_csv(here("data/vehicle_junction_location.csv")) %>% 
  clean_names()

vehicle_skidding_and_overturning_raw <- read_csv(here("data/vehicle_skidding_and_overturning.csv")) %>% 
  clean_names()

vehicle_hit_object_in_carriageway_raw <- read_csv(here("data/vehicle_hit_object_in_carriageway.csv")) %>% 
  clean_names()

vehicle_vehicle_leaving_carriageway_raw <- read_csv(here("data/vehicle_vehicle_leaving_carriageway.csv")) %>% 
  clean_names()

vehicle_hit_object_off_carriageway_raw <- read_csv(here("data/vehicle_hit_object_off_carriageway.csv")) %>% 
  clean_names()

vehicle_first_point_of_impact_raw <- read_csv(here("data/vehicle_first_point_of_impact.csv")) %>% 
  clean_names()

vehicle_vehicle_left_hand_drive_raw <- read_csv(here("data/vehicle_vehicle_left_hand_drive.csv")) %>% 
  clean_names()

vehicle_journey_purpose_of_driver_raw <- read_csv(here("data/vehicle_journey_purpose_of_driver.csv")) %>% 
  clean_names()

vehicle_sex_of_driver_raw <- read_csv(here("data/vehicle_sex_of_driver.csv")) %>% 
  clean_names()

vehicle_age_band_of_driver_raw <- read_csv(here("data/vehicle_age_band_of_driver.csv")) %>% 
  clean_names()

vehicle_propulsion_code_raw <- read_csv(here("data/vehicle_propulsion_code.csv")) %>% 
  clean_names()

vehicle_driver_imd_decile_raw <- read_csv(here("data/vehicle_driver_imd_decile.csv")) %>% 
  clean_names()

vehicle_driver_home_area_type_raw <- read_csv(here("data/vehicle_driver_home_area_type.csv")) %>% 
  clean_names()
```

```{r merge-vehicle-tables}
vehicle_clean <- vehicle_raw %>% 
  filter(vehicle_raw$vehicle_type != -1,
         vehicle_raw$towing_and_articulation != -1,
         vehicle_raw$vehicle_manoeuvre != 9,
         vehicle_raw$vehicle_manoeuvre != 99,
         vehicle_raw$vehicle_manoeuvre != -1,
         vehicle_raw$vehicle_direction_from != 9,
         vehicle_raw$vehicle_direction_to != 9,
         vehicle_raw$vehicle_location_restricted_lane != 99,
         vehicle_raw$vehicle_location_restricted_lane != -1,
         vehicle_raw$junction_location != 9,
         vehicle_raw$junction_location != -1,
         vehicle_raw$skidding_and_overturning != 9,
         vehicle_raw$skidding_and_overturning != -1,
         vehicle_raw$hit_object_in_carriageway != 99,
         vehicle_raw$hit_object_in_carriageway != -1,
         vehicle_raw$vehicle_leaving_carriageway != 9,
         vehicle_raw$vehicle_leaving_carriageway != -1,
         vehicle_raw$hit_object_off_carriageway != 99,
         vehicle_raw$hit_object_off_carriageway != -1,
         vehicle_raw$first_point_of_impact != 9,
         vehicle_raw$first_point_of_impact != -1,
         vehicle_raw$vehicle_left_hand_drive != 9,
         vehicle_raw$vehicle_left_hand_drive != -1,
         vehicle_raw$journey_purpose_of_driver != 6,
         vehicle_raw$journey_purpose_of_driver != 15,
         vehicle_raw$journey_purpose_of_driver != -1,
         vehicle_raw$sex_of_driver != -1,
         vehicle_raw$age_of_driver != -1,
         vehicle_raw$age_band_of_driver != -1,
         vehicle_raw$engine_capacity_cc != -1,
         vehicle_raw$propulsion_code != -1,
         vehicle_raw$generic_make_model != -1,
         vehicle_raw$driver_imd_decile != -1,
         vehicle_raw$driver_home_area_type != -1)

vehicle_clean_merged <- vehicle_clean %>% 
  inner_join(vehicle_vehicle_type_raw, by = "vehicle_type") %>% 
  inner_join(vehicle_towing_and_articulation_raw, by = "towing_and_articulation") %>% 
  inner_join(vehicle_vehicle_manoeuvre_raw, by = "vehicle_manoeuvre") %>% 
  inner_join(vehicle_vehicle_direction_from_raw, by = "vehicle_direction_from") %>% 
  inner_join(vehicle_vehicle_direction_to_raw, by = "vehicle_direction_to") %>% 
  inner_join(vehicle_vehicle_location_restricted_lane_raw, by = "vehicle_location_restricted_lane") %>% 
  inner_join(vehicle_junction_location_raw, by = "junction_location") %>% 
  inner_join(vehicle_skidding_and_overturning_raw, by = "skidding_and_overturning") %>% 
  inner_join(vehicle_hit_object_in_carriageway_raw, by = "hit_object_in_carriageway") %>% 
  inner_join(vehicle_vehicle_leaving_carriageway_raw, by = "vehicle_leaving_carriageway") %>% 
  inner_join(vehicle_hit_object_off_carriageway_raw, by = "hit_object_off_carriageway") %>% 
  inner_join(vehicle_first_point_of_impact_raw, by = "first_point_of_impact") %>% 
  inner_join(vehicle_vehicle_left_hand_drive_raw, by = "vehicle_left_hand_drive") %>% 
  inner_join(vehicle_journey_purpose_of_driver_raw, by = "journey_purpose_of_driver") %>% 
  inner_join(vehicle_sex_of_driver_raw, by = "sex_of_driver") %>%
  inner_join(vehicle_age_band_of_driver_raw, by = "age_band_of_driver") %>% 
  inner_join(vehicle_propulsion_code_raw, by = "propulsion_code") %>%
  inner_join(vehicle_driver_imd_decile_raw, by = "driver_imd_decile") %>% 
  inner_join(vehicle_driver_home_area_type_raw, by = "driver_home_area_type") %>% 
  select(-x3)

```